### ISSUE TITLE
Sample Epic: Use as a guide for NBL-sponsored external contribution

### ISSUE THREAD

**Issue by jeffgdotorg** [netbox-community/netbox#16368]
### NetBox version

v4.0.3

### Feature type

Change to existing functionality

### Proposed functionality

Update the NetBox v4.1 user interface to include more images of kittens, including in the following aspects:

- [ ] Replace NetBox logo with adorable kitten giving quizzical look #9999999
- [ ] Add sleepy kitten lounging atop rack in rack elevation #9999998
- [ ] Change nav menu category icons with various kitten silhouettes #9999997

### Use case

Intensive user research has revealed that NetBox users overwhelmingly bemoan the lack of kitten imagery in our user interface. Designing, documenting, and automating networks is less fun than it could be, and kittens are the clear solution.

### Database changes

None.

### External dependencies

None.

**Comment by jeffgdotorg** [comment]
This is a sample issue, resolving as not planned. Sorry, kittens.
