### ISSUE TITLE
Contrast Issues

### ISSUE THREAD

**Issue by andrewgormley** [netbox-community/netbox#16390]
### NetBox version

v4.0.3

### Feature type

Change to existing functionality

### Proposed functionality

Fix low contrast issues across the app that were found using Google Lighthouse and WAVE

Format:
(Location) Issue [Theme, Occurrences]

- [ ] (Navigation) Low contrast for side navigation sub-menu sub-headers [dark, global]
- [ ] (Dashboard) Module headers low contrast text [both, single]
- [ ] (Dashboard) Body copy low contrast on NetBox news [dark, single]
- [ ] (Footer) date and version text low contrast [dark, global]
- [ ] (Header) secondary text low contrast [dark, global]
- [ ] (Tables) Low contrast on pagination controls below tables [dark, multiple]
- [ ] (Tables) low contrast on some table headers [dark, multiple]
- [ ] (Tables) low contrast on table empty state text [dark, multiple]
- [ ] (List page) low contrast on buttons [both, multiple]
- [ ] (Toast) low contrast for warning toast [light, multiple]
- [ ] (Racks) low contrast labels [both, multiple]
- [ ] (Racks) low contrast download svg button [dark, multiple]
- [ ] (Object) low contrast on object title sub items eg. created 2020-10-10 [dark, multiple]
- [ ] (Breadcrumbs) low contrast on dark mode [dark, multiple]
- [ ] (Buttons) focus state on buttons is missing focus ring causing contrast and CVD issue [both, global]
- [ ] (Misc)Low contrast on dark tabular menu text [dark, multiple]
- [ ] (Misc)Low contrast on placeholder module placeholder text [dark, multiple]
- [ ] (Misc)Low contrast on form error text [both, multiple]
- [ ] (Misc)Low contrast on cancel button [dark, multiple]
- [ ] (Misc)Low contrast on create combo button [dark, multiple]
- [ ] (Misc)Low contrast in-line hyperlink [light, single]

### Use case

An accessibility audit revealed many contrast issues with the current application. The above changes will address those low contrast issues, fixing these issues will ensure that users with Colour Vision Deficiency (CVD) will come across far less issues.

```[tasklist]
### Tasks
```

**Comment by bobbwest** [comment]
Also highlighted/selected text in dark mode, although this is slightly better in v4.0.5.

**Comment by jeremystretch** [comment]
Closing this as the tasks above have been broken out into #16647, #16648, #16649, #16650, and #16651.
